services:
  pgAdmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:?required}
    container_name: pgAdmin
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.docker/pgAdmin/data:/var/lib/pgadmin
      - ./.docker/pgAdmin/backups:/backups
    networks:
      - traefik-network
      - postgres-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network

      - traefik.http.routers.pgAdmin.rule=Host(`${PGADMIN_SERVER_HOSTNAME:?required}`)
      - traefik.http.routers.pgAdmin.entrypoints=https
      - traefik.http.routers.pgAdmin.tls.certresolver=cloudflare
      - traefik.http.routers.pgAdmin.middlewares=trusted@file
      - traefik.http.routers.pgAdmin.service=pgAdmin

      # Services
      - traefik.http.services.pgAdmin.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


networks:
  traefik-network:
    external: true
  postgres-network:
    external: true
